apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config

data:
  fluent.conf: |
    <source>
      @type tail

      path /var/log/containers/*.log

      pos_file /fluentd/log/fluentd.pos

      tag kubernetes.*

      read_from_head true

      <parse>
        @type cri
      </parse>
    </source>

    <filter kubernetes.**>
      @type grep

      <regexp>
        key $.kubernetes.pod_name
        pattern k8s-demo
      </regexp>
    </filter>

    # <match **>
    #   @type stdout
    # </match>
    <match fluent.warn>
      @type null
    </match>

    <match **>
      @type opensearch

      host opensearch
      port 9200

      scheme https
      ssl_verify false
      ssl_version TLSv1_2

      user admin
      password GuEsT456@@789
      auth_method basic

      logstash_format true
      logstash_prefix k8s
      include_tag_key true
      tag_key fluent_tag

      <buffer>
        @type file
        path /fluentd/buffer/opensearch
        flush_interval 5s
        retry_forever true
      </buffer>
    </match>